"""
VidkNot - Video Knowledge, Knotted.
Copyright (c) 2026 VidkNot Team

This software is licensed under the MIT License.
See LICENSE file in the project root for details.

https://github.com/suonian/vidknot
"""

# -*- coding: utf-8 -*-
"""
VidkNot Cookie 提供者

支持多策略获取抖音 Cookie（按优先级）：
1. 用户提供的 Cookie 文件（JSON / Netscape 格式）
2. CDP（Chrome DevTools Protocol）从已登录浏览器获取
3. browser_cookie3 从浏览器数据库读取（fallback，需管理员权限）

所有策略统一输出为 Netscape 格式的 Cookie 文件路径，供 yt-dlp 使用。
"""

import json
import os
import re
import tempfile
from pathlib import Path
from typing import Dict, Any, Optional, Tuple

from ..utils.exceptions import CookieExportError
from ..utils.logger import get_logger

logger = get_logger(__name__)

# ===== Netscape Cookie 格式常量 =====

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# This file was generated by VidkNot.\n\n"

# ===== 公共接口 =====


def get_douyin_cookie_file(
    explicit_path: Optional[str] = None,
    enable_cdp: bool = True,
    enable_browser_cookie3: bool = True,
) -> Tuple[Optional[str], str]:
    """
    获取抖音 Cookie 文件（Netscape 格式）

    Args:
        explicit_path: 用户显式指定的 Cookie 文件路径
        enable_cdp: 是否尝试通过 CDP 从浏览器获取
        enable_browser_cookie3: 是否尝试 browser_cookie3

    Returns:
        (cookie_file_path, strategy_name)
        - cookie_file_path: Netscape 格式 Cookie 文件路径，None 表示获取失败
        - strategy_name: 使用的策略名称（用于日志和调试）
    """
    strategies = []

    # 策略 1: 用户提供的文件
    if explicit_path:
        strategies.append(("file", lambda: _from_file(explicit_path)))

    # 策略 2: 自动探测的常见路径
    auto_paths = _find_auto_cookie_paths()
    for p in auto_paths:
        strategies.append(("auto_file", lambda p=p: _from_file(p)))

    # 策略 3: CDP
    if enable_cdp:
        strategies.append(("cdp", _from_cdp))

    # 策略 4: browser_cookie3
    if enable_browser_cookie3:
        strategies.append(("browser_cookie3", _from_browser_cookie3))

    last_error = None
    for name, getter in strategies:
        try:
            cookie_file = getter()
            if cookie_file and Path(cookie_file).exists():
                logger.info(f"[CookieProvider] Cookie 获取成功: strategy={name}, path={cookie_file}")
                return cookie_file, name
        except Exception as e:
            last_error = e
            logger.debug(f"[CookieProvider] strategy={name} 失败: {e}")
            continue

    logger.warning(f"[CookieProvider] 所有策略均失败，最后错误: {last_error}")
    return None, "failed"


# ===== 策略实现 =====


def _from_file(path: str) -> Optional[str]:
    """从用户提供的文件读取 Cookie（支持 JSON 和 Netscape 格式）"""
    file_path = Path(path)
    if not file_path.exists():
        return None

    content = file_path.read_text(encoding="utf-8", errors="ignore")

    # 判断格式
    stripped = content.strip()
    if stripped.startswith("{") or stripped.startswith("["):
        # JSON 格式（如 EditThisCookie 导出）
        return _convert_json_to_netscape(content)
    elif "# Netscape HTTP Cookie File" in content:
        # 已经是 Netscape 格式，但需要确保子域名扩展（供 yt-dlp 兼容）
        return _expand_netscape_domains(content)


def _expand_netscape_domains(content: str) -> str:
    """
    将已有 Netscape 格式文件进行子域名扩展，
    确保关键 Cookie（如 s_v_web_id）在所有 douyin 相关子域都能被发送。

    yt-dlp 请求 iesdouyin.com，但 Cookie 通常只在 www.douyin.com，
    故将 www.douyin.com 的 Cookie 复制到 iesdouyin.com。
    """
    lines = content.strip().split("\n")
    header = lines[0] if lines and lines[0].startswith("#") else NETSCAPE_HEADER
    data_lines = lines[1:] if lines and lines[0].startswith("#") else lines

    written = {}  # (domain, name) -> line 去重
    result_lines = [header]

    for line in data_lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue

        domain, domain_specified, path, secure, expiry, name, value = parts[:7]
        key = (domain, name)
        if key in written:
            continue

        result_lines.append(
            f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expiry}\t{name}\t{value}"
        )
        written[key] = line

        # 扩展 www.douyin.com 和 douyin.com 的关键 Cookie 到 iesdouyin.com
        if domain in ("www.douyin.com", "douyin.com") and name in (
            "s_v_web_id", "ttwid", "sessionid", "sid_tt"
        ):
            # iesdouyin.com 不以 . 开头 → domain_specified = FALSE
            result_lines.append(
                f"iesdouyin.com\tFALSE\t/\t{secure}\t{expiry}\t{name}\t{value}"
            )

    temp_file = tempfile.mktemp(suffix=".txt")
    with open(temp_file, "w", encoding="utf-8") as f:
        f.write("\n".join(result_lines) + "\n")

    return temp_file


def _convert_json_to_netscape(json_content: str) -> str:
    """将 JSON 格式 Cookie（EditThisCookie 等）转换为 Netscape 格式"""
    cookies = json.loads(json_content)
    if isinstance(cookies, dict):
        # 可能是按域名分组的格式
        flat = []
        for domain, cookie_list in cookies.items():
            if isinstance(cookie_list, list):
                flat.extend(cookie_list)
        cookies = flat

    temp_file = tempfile.mktemp(suffix=".txt")
    written = set()

    def _write_cookie(f, domain, path, secure, expiry, name, value):
        domain_specified = "TRUE" if domain.startswith(".") else "FALSE"
        line = f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
        key = (domain, name, value)
        if key not in written:
            f.write(line)
            written.add(key)

    with open(temp_file, "w", encoding="utf-8") as f:
        f.write(NETSCAPE_HEADER)
        for c in cookies:
            domain = c.get("domain", c.get("Domain", ""))
            path = c.get("path", c.get("Path", "/"))
            secure = "TRUE" if c.get("secure", c.get("Secure", False)) else "FALSE"
            expiry = str(c.get("expirationDate", c.get("expires", 0)) or 0).split(".")[0]
            name = c.get("name", c.get("Name", ""))
            value = c.get("value", c.get("Value", ""))

            # 写入原始 domain
            _write_cookie(f, domain, path, secure, expiry, name, value)

            # 对 douyin.com 子域名，额外写入 .douyin.com 和 iesdouyin.com
            # 使 Cookie 能匹配 yt-dlp 可能请求的所有子域
            if domain in ("www.douyin.com", "douyin.com") and name:
                _write_cookie(f, ".douyin.com", path, secure, expiry, name, value)
                _write_cookie(f, "iesdouyin.com", "/", secure, expiry, name, value)

    return temp_file


def _find_auto_cookie_paths() -> list:
    """自动探测的常见 Cookie 文件路径"""
    candidates = [
        # 项目级
        Path.cwd() / "cookies" / "douyin.txt",
        Path.cwd() / "cookies" / "douyin.json",
        # 用户级
        Path.home() / ".vidknot" / "cookies" / "douyin.txt",
        Path.home() / ".vidknot" / "cookies" / "douyin.json",
        # 源码级（兼容旧路径）
        Path(__file__).parent.parent.parent / "cookies" / "douyin.txt",
        Path(__file__).parent.parent.parent / "cookies" / "douyin.json",
    ]
    return [str(p) for p in candidates]


def _from_cdp() -> Optional[str]:
    """通过 Chrome DevTools Protocol 从浏览器获取 Cookie"""
    import urllib.request

    # 探测常见 Remote Debugging 端口
    ports = [9222, 9223, 9224, 9225, 9333]
    ws_url = None
    port_found = None

    for port in ports:
        try:
            req = urllib.request.Request(
                f"http://localhost:{port}/json",
                headers={"Accept": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=2) as resp:
                import json
                data = json.loads(resp.read().decode("utf-8"))
                if data and isinstance(data, list) and len(data) > 0:
                    ws_url = data[0].get("webSocketDebuggerUrl")
                    port_found = port
                    break
        except Exception:
            continue

    if not ws_url:
        raise CookieExportError("未找到开启 Remote Debugging 的浏览器")

    logger.debug(f"[CookieProvider] CDP 连接到端口 {port_found}: {ws_url[:60]}...")

    # 使用 websocket-client 发送 Network.getCookies 命令
    try:
        import websocket
    except ImportError:
        raise CookieExportError("websocket-client 未安装，无法使用 CDP 获取 Cookie")

    ws = websocket.create_connection(ws_url, timeout=10)
    try:
        ws.send(json.dumps({"id": 1, "method": "Network.getCookies"}))
        resp = json.loads(ws.recv())
        cookies = resp.get("result", {}).get("cookies", [])
    finally:
        ws.close()

    # 过滤 douyin.com 域的 Cookie
    douyin_cookies = [c for c in cookies if "douyin" in c.get("domain", "")]
    if not douyin_cookies:
        raise CookieExportError("浏览器中未找到 douyin.com 的 Cookie（请先登录抖音）")

    # 写入 Netscape 格式临时文件
    temp_file = tempfile.mktemp(suffix=".txt")
    written = set()

    def _write_cookie(f, domain, path, secure, expiry, name, value):
        domain_specified = "TRUE" if domain.startswith(".") else "FALSE"
        line = f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
        key = (domain, name, value)
        if key not in written:
            f.write(line)
            written.add(key)

    with open(temp_file, "w", encoding="utf-8") as f:
        f.write(NETSCAPE_HEADER)
        for c in douyin_cookies:
            domain = c["domain"]
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expiry = str(c.get("expires", 0) or 0).split(".")[0]
            name = c["name"]
            value = c["value"]

            _write_cookie(f, domain, path, secure, expiry, name, value)
            # 子域名扩展
            if domain in ("www.douyin.com", "douyin.com") and name:
                _write_cookie(f, ".douyin.com", path, secure, expiry, name, value)
                _write_cookie(f, "iesdouyin.com", "/", secure, expiry, name, value)

    logger.info(f"[CookieProvider] CDP 成功获取 {len(douyin_cookies)} 个 Cookie")
    return temp_file


def _from_browser_cookie3() -> Optional[str]:
    """使用 browser_cookie3 从浏览器数据库读取 Cookie"""
    try:
        import browser_cookie3
    except ImportError:
        raise CookieExportError("browser_cookie3 未安装")

    for name, getter in [
        ("edge", lambda: browser_cookie3.edge(domain_name="douyin.com")),
        ("chrome", lambda: browser_cookie3.chrome(domain_name="douyin.com")),
        ("firefox", lambda: browser_cookie3.firefox(domain_name="douyin.com")),
    ]:
        try:
            cookies = getter()
            if not cookies:
                continue

            temp_file = tempfile.mktemp(suffix=".txt")
            with open(temp_file, "w", encoding="utf-8") as f:
                f.write(NETSCAPE_HEADER)
                for c in cookies:
                    domain_specified = "TRUE" if c.domain.startswith(".") else "FALSE"
                    f.write(
                        f"{c.domain}\t{domain_specified}\t{c.path}\t"
                        f"{'TRUE' if c.secure else 'FALSE'}\t"
                        f"{int(c.expires) if c.expires else 0}\t"
                        f"{c.name}\t{c.value}\n"
                    )
            logger.info(f"[CookieProvider] browser_cookie3 从 {name} 获取成功")
            return temp_file
        except Exception as e:
            logger.debug(f"[CookieProvider] browser_cookie3 ({name}) 失败: {e}")
            continue

    raise CookieExportError("browser_cookie3 无法从任何浏览器读取 Cookie")


# ===== 工具函数 =====


def cleanup_temp_cookie(file_path: Optional[str]) -> None:
    """清理临时 Cookie 文件"""
    if not file_path:
        return
    try:
        p = Path(file_path)
        if p.exists() and p.parent == Path(tempfile.gettempdir()):
            p.unlink()
            logger.debug(f"[CookieProvider] 清理临时 Cookie: {file_path}")
    except Exception as e:
        logger.debug(f"[CookieProvider] 清理临时 Cookie 失败: {e}")


# -----------------------------------------------------------------------------
# VidkNot - Video Knowledge, Knotted.
# -----------------------------------------------------------------------------
# Copyright (c) 2026 VidkNot Team
# 
# This software is licensed under the MIT License.
# See LICENSE file in the project root for details.
# 
# Repository: https://github.com/suonian/vidknot
# -----------------------------------------------------------------------------

